language: node_js
env:
- MOCHA_REPORTER=spec
node_js:
- '0.11'
- '0.10'
notifications:
  on_success: always
  on_failure: always
  on_start: always
  webhooks:
  - http://ngs-hubot.herokuapp.com/travisci/hooks
deploy:
  provider: npm
  email: a@ngs.io
  api_key:
    secure: ZmHA4Q4qM9Zb42Lea/yFEa4CR1oNPpX2fqYGd+L64X/Nh1bVcnSykRV2HtXZ1jLLP99+3ASKyykbFhq/IcAIQC/iJ18mw6yK8GY5oVckFBZrRDIhH6drvkzcBUzXdXFLD8GEljvz8BGcdlUzbE23A8G6mamsOTKrcBoiq+jjfyg=
  on:
    tags: true
    all_branches: true
    repo: ngs/hubot-qiita
